GET http://localhost:8080/api/student

###

POST http://localhost:8080/api/student
Content-Type: application/json

{
"firstName": "Tarik",
"lastName": "Hosic",
"age": 19
}

###

#New student with teacher
POST http://localhost:8080/api/student
Content-Type: application/json

{
  "firstName": "Moritz",
  "lastName": "Eichhorn",
  "age": 19,
  "teacher": {"id":  1}
}

###

#New student with teacher and classRoom
POST http://localhost:8080/api/student
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kaufmann",
  "age": 19,
  "teacher": {"id":  1},
  "classRoom": {"className":  "5AHIF"}
}

###
# Admin
POST http://localhost:8080/api/student/clear
Authorization: Basic scott jb0ss

###

###

GET http://localhost:8080/api/student/info
Authorization: Basic noadmin n0Adm1n
