GET http://localhost:8080/api/teacher

###

POST http://localhost:8080/api/teacher
Content-Type: application/json

{
  "firstName": "Riccarda",
  "lastName": "Reiter"
}

###

POST http://localhost:8080/api/teacher/init-teachers